### PR TITLE
Bulk upgrade python dependencies

### PR DESCRIPTION
**Pull request by norbye**
* Remove remaining traces of python 3.7 usage

Realized that the upgrading process was a bit quicker when I updated the actual dependencies from the .in files and not all of their dependencies in the .txt files (:

### CODE REVIEW

**Review by SmithPeder — APPROVED** [review]
Nice!
There is actually one smaaal python 3.8 part left

This part (and all similar parts)
https://github.com/webkom/committee-admissions/blob/eb934b2604f485662085c988cf7928dbfeb11716/.drone.yml#L19

lego-testbase currently runs python 3.8 as the updated version is not pushed to dockerhub yet :D

**Comment by ivarnakken** [comment]
> lego-testbase currently runs python 3.8 as the updated version is not pushed to dockerhub yet :D

Not entirely correct. `lego-testbase` is simply tagged with the correct python version. See https://hub.docker.com/r/abakus/lego-testbase/tags. `:latest` has therefore not been updated in 3 years. I vouch for tagging the image in drone, instead of running on latest. By doing so, this repo won't break once we bump python for lego 😄

**Comment by SmithPeder** [comment]
I see you pushed 3.9 3 days ago, nice! Push that to latest as well.
image
I agree that the drone files that use `lego-testbase` should use that tagged version

**Comment by ivarnakken** [comment]
> Push that to latest as well.

Sure, but that doesn't change my point. You _should_ never run latest on anything. So tag the version here, and we're good.

**Comment by SmithPeder** [comment]
> ... but that doesn't change my point. You should never run latest on anything

image

Bro that's what I said

**Comment by norbye** [comment]
All usages of lego-testbase within this repo should use the tagged version now(:

**Review by ivarnakken — APPROVED** [review]

**Pull request merged**
