### PR TITLE
Add cancel edit button

### LINKED ISSUE #254: User cannot cancel editing aplication
If you press `edit application`, you cannot cancel the editing. This is also stored in session value, so refreshing will not  cancel the edit. A user should be able to cancel the edit if they have previously sent the application.

### PR DESCRIPTION
**Pull request by erlingfn**
Add a button to allow a user to cancel editing the users application. Suggestions for design encouraged! Fixes #254 .
Some screenshots:
Desktop
image
Mobile
image

### CODE REVIEW

**Comment by LudvigHz** [comment]
Awesome! :rocket:
Maybe the desktop button is a bit large :thinking:

**Comment by SmithPeder** [comment]
This is the biggest button I've ever seen 🥇

**Comment by erlingfn** [comment]
New and improved. Desktop:
image
Mobile:
image

**Comment by SmithPeder** [comment]
That's better

**Comment by erlingfn** [comment]
Should hold our horses on merging this one. Due to the fact that the receipt-banner("Vi har mottat din søknad") is shown whenever the component containing it is rendered, if a user cancels editing without having submitted the page will still show a receipt indicating that we have received the application without it being submitted. This could lead to some confusion.

**Pull request merged**
