### PR TITLE
Upgrade a bunch of node packages, upgrade node to v16

### PR DESCRIPTION
**Pull request by norbye**
* Update js code formatting to adhere to updated prettier rules
* Update css code formatting to adhere to updated stylelint rules
* Update all devDependencies except webpack and webpack-related devDependencies
* Update all dependencies that are not marked as "Major Update backward-incompatible updates" by `yarn upgrade-interactive --latest`

### CODE REVIEW

**Review by ivarnakken — APPROVED** [review]
Nice 💯 This is all much needed on this repo

**Comment by norbye** [comment]
Wanted to get all dependencies updated before merging this pr, but I most likely won't have any time for dependencies for the next two weeks so I'm uploading this so this work is already merged if anyone else wants to take a look at it in the meantime.

Got stuck on one of many breaking changes in webpack 5 and its dependencies. Pushing a commit with my work so far soon in another branch if anyone wants to have a look(:

**Review by LudvigHz — APPROVED** [review]

**Comment by norbye** [comment]
> Nice! Should get the node 10 changed in the Dockerfile as well. 😳

@SmithPeder anywhere else it has to be changed / any other changes needed?

**Review by SmithPeder — APPROVED** [review]
👍

**Pull request merged**
